CREATE DATABASE jupyterhub;
CREATE USER jupyterhub WITH ENCRYPTED PASSWORD '$JPY_PSQL_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE jupyterhub TO jupyterhub;
CREATE DATABASE checkpoints;
CREATE USER pgcontent WITH ENCRYPTED PASSWORD '$CHECKPOINTS_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE checkpoints TO pgcontent;
