#################
# Prerequisites #
#################

FROM jupyterhub/jupyterhub

# Sync timezone (for logs)

ENV TZ=Europe/Berlin
RUN echo $TZ | tee /etc/timezone
RUN dpkg-reconfigure --frontend noninteractive tzdata

# For debugging in docker

RUN export TERM=xterm

# nano only for debugging

RUN apt-get update \
    && apt-get install -y libpq-dev nano \
    && apt-get autoremove -y

RUN pip install psycopg2 jupyter nose netifaces

############
# Security #
############

RUN mkdir -p /etc/certs && touch /etc/certs/ssl.key && touch /etc/certs/ssl.crt

RUN openssl req -x509 -nodes -days 730 -newkey rsa:2048 \ 
                 -subj "/C=DE/ST=BER/L=BER/O=HUB/CN=jubHUB" \ 
                 -keyout /etc/certs/ssl.key -out /etc/certs/ssl.crt

RUN export CONFIGPROXY_AUTH_TOKEN=`openssl rand -hex 32`

#################
# Checkpoints   #
#################

RUN pip install -e git+https://github.com/dateutil/dateutil.git#egg=dateutil

RUN pip install -e git+https://github.com/quantopian/pgcontents#egg=pgcontents

##################
# User managment #
##################

RUN useradd -m -G shadow -p $(openssl passwd -1 admin) admin
RUN chown admin /srv/jupyterhub

RUN for name in user1 user2 user3 ; do useradd -m -p $(openssl passwd -1 $name) $name; done

##############
# Add config #
##############

COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py

RUN mkdir -p /etc/jupyter

COPY jupyter_notebook_config.py /etc/jupyter

###############################
# Get rid of Server Error 500 #
###############################

# Careful; uncommenting prevents opening of singleuser servers. 
# On the other hand, now jupyterhub runs as root, which is a security issue
#USER rhea

# Second CMD should override the one defined in jupyterhub/jupyterhub
ADD startup.sh /srv/jupyterhub

CMD ["/srv/jupyterhub/startup.sh"]

